# toy_en_de.yaml

## Where the samples will be written
save_data: /content/minangNLP/translation/wiki_data/run/example
## Where the vocab(s) will be written
src_vocab: /content/minangNLP/translation/wiki_data/run/example.vocab.tgt
tgt_vocab: /content/minangNLP/translation/wiki_data/run/example.vocab.src
# Prevent overwriting existing files in the folder
overwrite: True
world_size: 1
gpu_ranks: [0]

# Where to save the checkpoints
save_model: toy-indmin/run/model
save_checkpoint_steps: 500
train_steps: 40000
valid_steps: 500
# Corpus opts:
data:
    corpus_1:
        path_tgt: /content/minangNLP/translation/wiki_data/src_train.txt
        path_src: /content/minangNLP/translation/wiki_data/tgt_train.txt
    valid:
        path_tgt: /content/minangNLP/translation/wiki_data/src_dev.txt
        path_src: /content/minangNLP/translation/wiki_data/tgt_dev.txt